services:
  linebot-agent-project:
    image: linebot-agent-project:latest
    container_name: linebot-agent-project
    ports:
      - 8001:8001
    volumes:
      - ./data:/data      
    environment:
        LINE_CHANNEL_SECRET : ${LINE_CHANNEL_SECRET}
        LINE_CHANNEL_ACCESS_TOKEN : ${LINE_CHANNEL_ACCESS_TOKEN}
        LINE_CHAT_HISTORY_LENGTH : ${LINE_CHAT_HISTORY_LENGTH}
        WEATHERMAP_API_KEY : ${WEATHERMAP_API_KEY}
        COMFYUI_WS_ENDPOINT : ${COMFYUI_WS_ENDPOINT}
        COMFYUI_WORKFLOW_PATH : ${COMFYUI_WORKFLOW_PATH}            
        OPENAI_COMPATIBLE_API_BASE_URL : ${OPENAI_COMPATIBLE_API_BASE_URL}
        OPENAI_COMPATIBLE_API_KEY : ${OPENAI_COMPATIBLE_API_KEY}
        OPENAI_COMPATIBLE_API_MODEL_NAME : ${OPENAI_COMPATIBLE_API_MODEL_NAME}
        REDIS_HOST_ADDRESS : ${REDIS_HOST_ADDRESS}
        REDIS_HOST_PORT : ${REDIS_HOST_PORT}
        GOOGLE_SEARCH_API_KEY : ${GOOGLE_SEARCH_API_KEY} #your_google_api_key
        GOOGLE_CX : ${GOOGLE_CX} #your_custom_search_engine_id
        SEARCH_ENGINE : ${SEARCH_ENGINE}  # or "duckduckgo" "google"   
        MINIO_ACCESS_KEY : ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY : ${MINIO_SECRET_KEY}
        MINIO_URL_API : ${MINIO_URL_API}
        MINIO_URL_WEBUI : ${MINIO_URL_WEBUI}
        MINIO_BUCKET  : ${MINIO_BUCKET}       
    restart: on-failure:5	      
    network_mode: host